version: 2

jobs:
  test:
    docker:
      - image: web3f/node-dind:v0.3.0
    steps:
      - checkout
      - setup_remote_docker
      - run: yarn
      - run:
          name: Run tests
          command: |
            yarn test


workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
